### ISSUE TITLE
Activation failed after restore

### ISSUE THREAD

**Issue by Halo-Michael** [Samgisaninja/SuccessionRestore#10]
Activation failed after restore on iPhoneSE, either directly connected to wifi activation or connected to a computer using iTunes activation, or using tools such as 3UTools. (Don't worry about me, I have used futurerestore to restore the system and can activate it afterwards.) I suspect it is related to my baseband version, because I am currently using 12.2 sep+baseband with iOS12.1.1.

**Comment by Samgisaninja** [comment]
if possible, can you please compile and run the `log-only` branch and send /var/mobile/log.txt?

EDIT: This branch will not actually restore the device or call mobile_obliterator

**Comment by Halo-Michael** [comment]
Sure
[log.txt](https://github.com/Samgisaninja/SuccessionRestore/files/3067097/log.txt)

**Comment by Samgisaninja** [comment]
would you be willing to join me on https://discord.gg/jb to test some stuff?

(if so, please ping me, I'm @Samg_is_a_Ninja#6113)

**Comment by Halo-Michael** [comment]
> would you be willing to join me on https://discord.gg/jb to test some stuff?
> 
> (if so, please ping me, I'm @Samg_is_a_Ninja#6113)

Do you means @Samg_is_a_Ninja#6111?

**Comment by Halo-Michael** [comment]
I just tested version 0.5.5 of Succession, it really works very well, I have successfully activated my SE after using it.

**Comment by Halo-Michael** [comment]
Still activation failed after restore on 0.5.5

**Comment by Samgisaninja** [comment]
> Samg\_is\_a\_Ninja#6111

No that was a test account lol, I’m #6113

**Comment by Samgisaninja** [comment]
This bug is confirmed present on the iPhone 8 Plus, confirmed absent on the iPhone 5s

**Comment by Samgisaninja** [comment]
Fixed in succession 0.7
