### ISSUE TITLE
Can't restore, filesustem isn't mounted 

### ISSUE THREAD

**Issue by chaqti** [Samgisaninja/SuccessionRestore#102]
I'm trying to restore but I get this 
![15815333239228001653704827960401](https://user-images.githubusercontent.com/59891768/74366656-51d60580-4dc8-11ea-90aa-097ce84a8c30.jpg)

**Comment by Samgisaninja** [comment]
This is caused by #89

**Comment by chaqti** [comment]
I'm stuck on attaching now

**Comment by Samgisaninja** [comment]
Also #89

**Comment by chaqti** [comment]
OK fixed issues now the device doesn't downgrade to 13.2.3 it goes back to 13.3 even when I put in dfu and jailbreak

**Comment by chaqti** [comment]
> Also #89

What about after restore zone it goes back to ups 13.3

**Comment by Samgisaninja** [comment]
That means you're downgrading... which succession isn't intended to do...
