### ISSUE TITLE
ERROR! Failed to create /private/var/COPY/mnt1.......

### ISSUE THREAD

**Issue by tomsmile0** [Samgisaninja/SuccessionRestore#104]
I am having trouble using succession to remove jailbreak. I have a device crash when I run "Prepare for restore!".
Ipad5,4
IOS: 13.3
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4209492/succession.log)

![EE2BBDA8-3208-4C3F-BA3F-93181AA297FB](https://user-images.githubusercontent.com/9924087/74601195-0ecca880-50ce-11ea-83fc-40faa02d3a2e.png)

**Comment by Samgisaninja** [comment]
This is a symptom of #89
