### ISSUE TITLE
Succession finishes, but doesn't restore.

### ISSUE THREAD

**Issue by Paradise-My-Colors** [Samgisaninja/SuccessionRestore#105]
Using iPad Air 2, ios 13.3.1, jailbroken via checkrain 0.9.8, succession v1.4.11 (and tried 1.3.8).
The tool works just fine using a provided 13.2.3 ipsw up till the end when it builds icons cache and reboots, i then force it to recovery mood immediately and re-jailbreak using checkrain 0.9.8, the device boots up, no "update successful", and i am still on ios 13.3.1 .
I read on another post that i should use some command to grant succession root access before it starts, tried it, same result.
Is there something I'm missing ? Or should i just wait for a fix in the next release ?
Sorry if the issue has been solved but couldn't find anything.
Thanks in advance.

**Comment by Samgisaninja** [comment]
you can’t downgrade with succession
