### ISSUE TITLE
Support for iPhone11 pro max on iOS13.3

### ISSUE THREAD

**Issue by LookoutY** [Samgisaninja/SuccessionRestore#106]
Hi sir, first thanks for your great work of Succession.
I try to restore my iPhone11 pro max (iOS13.3) by Succession 1.4.11, but it didn't erase my user documets as well as configurations. I wonder is Succession fully supporting iPhone11 pro max? Or the phone will be supported in the next edition?
Thank you.

**Comment by Samgisaninja** [comment]
Yes
