### ISSUE TITLE
 stuck on rebuilding icon cache

### ISSUE THREAD

**Issue by SoaringJim** [Samgisaninja/SuccessionRestore#107]
The iOS version of my iPhone XS is 13.3 and I was trying to erase my iPhone with your Succession. Unfortunately, it stuck on the last step: rebuilding icon cache. I have waited for 1 hour but it still stuck on this step. Finally, I forced my iPhone to restart and erased my iPhone in the system settings. After that, my iPhone is truly erased. However, my Face ID didn’t work and I can receive SMS anymore.

**Comment by Samgisaninja** [comment]
These are both known issues caused by the unc0ver jailbreak. Fixes will come soon. For now, use unc0ver to restore rootfs. Assuming there is no hardware damage, FaceID/SMS functionality will return.

**Comment by 1c383r9** [comment]
Mine is an XR on 13.1.3 with unc0ver 4.2 and the latest succession release( installed from bigboss, should be 1.4.11). Got stuck on rebuilding icon cache as well. Obviously a successful restore couldn't be completed at the time. I don't think of giving it a system reset as a good idea right now. Instead:

Reboot once after it got stuck, and open unc0ver to perform restorerootfs.

Luckily my ios 13.1.3 and other applications are saved and it seems not to be any weird stuff happening.

Sincerely hope for a future solution.
Best regards. @Samgisaninja
