### ISSUE TITLE
Restore Succeeded - Rebuilding Icon Cache

### ISSUE THREAD

**Issue by Georgecox7** [Samgisaninja/SuccessionRestore#109]
Model iPhone10,6
iOS Version 13.3
iOS Build 17C54

Succession Version 1.4.11 (also tried 1.4.7)

Didn’t get past ‘Restore Succeeded - Rebuilding icon cache’ stage after I left it on overnight, went to sleep with the pop up box showing - woke up 9 hours later with it showing the same thing

Is there anyway to fix it

**Comment by Samgisaninja** [comment]
This is an issue caused by the unc0ver jailbreak. I'll have a workaround out for it in the next version. For now, reboot and run it on checkra1n.

**Comment by mondolfo** [comment]
Same for me..i use checkra1n v. 0.9.7. Just stuck on Restore Succeeded! Rebuild icon cache, please wait...

after that phone need restore from itunes... because his stop working
