### ISSUE TITLE
ios 9 "Can´t restore, filesystem isn´t mounted"

### ISSUE THREAD

**Issue by iFhone4s** [Samgisaninja/SuccessionRestore#112]
Hi, Thx for support!
I try use succession on iphone 4s ios 9.3.2, decrypted ipsw and all ok, but when press erase: Can´t restore, filesystem isn´t mounted.
Succession.log :
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 92: Mountpoint exists, continuing
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 167: attachDiskImage called!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 262: Using comex attach for attach
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 275: attach output is: disk2

[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 278: disk2,

2
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 296: found attached diskname disk2
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 303: sending /dev/disk2 to mountRestoreDisk
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 338: prepareMountAttachedDisk called!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 350: Identified filesystem as HFS!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:31 +0000] Line 375: mounting complete!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:33 +0000] Line 392: tappedRestoreButton called
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:33 +0000] Line 435: no apfs snapshot operations requested
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:33 +0000] Line 441: showRestoreAlert called!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:19:33 +0000] Line 502: ERROR! Can't restore, filesystem isn't mounted.
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:57 +0000] Line 92: Mountpoint exists, continuing
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:57 +0000] Line 167: attachDiskImage called!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:57 +0000] Line 262: Using comex attach for attach
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:58 +0000] Line 275: attach output is: disk3

[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:58 +0000] Line 278: disk3,

2
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:58 +0000] Line 296: found attached diskname disk3
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:58 +0000] Line 303: sending /dev/disk3 to mountRestoreDisk
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:58 +0000] Line 338: prepareMountAttachedDisk called!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:58 +0000] Line 350: Identified filesystem as HFS!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:47:58 +0000] Line 375: mounting complete!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:48:00 +0000] Line 392: tappedRestoreButton called
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:48:00 +0000] Line 435: no apfs snapshot operations requested
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:48:00 +0000] Line 441: showRestoreAlert called!
[SUCCESSIONLOG 1.4.11: 2020-03-02 11:48:00 +0000] Line 502: ERROR! Can't restore, filesystem isn't mounted.

Help please!

**Comment by Samgisaninja** [comment]
argh, somewhere in there I messed up the parsing of attach, can you please:

1. cause this issue again
2. run ls -l /dev
3. send output of that command here

**Comment by iFhone4s** [comment]
iPhone-de-iFhone4s:/ root# ls -l /dev
total 0
crw-rw-rw- 1 root wheel 20, 0 Mar 8 23:27 aes_0
crw------- 1 root wheel 23, 0 Mar 8 23:38 bpf0
crw------- 1 root wheel 23, 1 Mar 8 23:27 bpf1
crw------- 1 root wheel 23, 2 Mar 8 23:27 bpf2
crw------- 1 root wheel 23, 3 Mar 8 23:27 bpf3
c------r-- 1 root wheel 13, 0 Mar 8 23:27 btreset
c------r-- 1 root wheel 14, 0 Mar 8 23:27 btwake
crw--w--w- 1 root wheel 0, 0 Mar 8 23:27 console
crw-rw-rw- 1 root wheel 7, 7 Mar 8 23:27 cu.bluetooth
crw-rw-rw- 1 root wheel 7, 5 Mar 8 23:27 cu.debug
crw-rw-rw- 1 root wheel 7, 3 Mar 8 23:27 cu.gas-gauge
crw-rw-rw- 1 root wheel 7, 1 Mar 8 23:27 cu.iap
brw-r----- 1 root operator 1, 0 Mar 8 23:27 disk0
brw-r----- 1 root operator 1, 1 Mar 8 23:27 disk0s1
brw-r----- 1 root operator 1, 2 Mar 8 23:27 disk0s1s1
brw-r----- 1 root operator 1, 3 Mar 8 23:27 disk0s1s2
brw-r----- 1 root operator 1, 4 Mar 8 23:31 disk1
brw-r----- 1 root operator 1, 5 Mar 8 23:38 disk2
crw-r--r-- 1 root wheel 9, 0 Mar 8 23:27 fsevents
crw------- 1 root wheel 6, 0 Mar 8 23:27 klog
crw-rw-rw- 1 root wheel 3, 2 Mar 8 23:39 null
crw------- 1 root wheel 8, 0 Mar 8 23:27 pf
crw------- 1 root wheel 8, 1 Mar 8 23:27 pfm
crw-rw-rw- 1 root tty 15, 1 Mar 8 23:39 ptmx
crw-rw-rw- 1 root wheel 5, 0 Mar 8 23:27 ptyp0
crw-rw-rw- 1 root wheel 5, 1 Mar 8 23:27 ptyp1
crw-rw-rw- 1 root wheel 5, 2 Mar 8 23:27 ptyp2
crw-rw-rw- 1 root wheel 5, 3 Mar 8 23:27 ptyp3
crw-rw-rw- 1 root wheel 5, 4 Mar 8 23:27 ptyp4
crw-rw-rw- 1 root wheel 5, 5 Mar 8 23:27 ptyp5
crw-rw-rw- 1 root wheel 5, 6 Mar 8 23:27 ptyp6
crw-rw-rw- 1 root wheel 5, 7 Mar 8 23:27 ptyp7
crw-rw-rw- 1 root wheel 5, 8 Mar 8 23:27 ptyp8
crw-rw-rw- 1 root wheel 5, 9 Mar 8 23:27 ptyp9
crw-rw-rw- 1 root wheel 5, 10 Mar 8 23:27 ptypa
crw-rw-rw- 1 root wheel 5, 11 Mar 8 23:27 ptypb
crw-rw-rw- 1 root wheel 5, 12 Mar 8 23:27 ptypc
crw-rw-rw- 1 root wheel 5, 13 Mar 8 23:27 ptypd
crw-rw-rw- 1 root wheel 5, 14 Mar 8 23:27 ptype
crw-rw-rw- 1 root wheel 5, 15 Mar 8 23:27 ptypf
crw-rw-rw- 1 root wheel 10, 0 Mar 8 23:27 random
crw-r----- 1 root operator 1, 0 Mar 8 23:27 rdisk0
crw-r----- 1 root operator 1, 1 Mar 8 23:27 rdisk0s1
crw-r----- 1 root operator 1, 2 Mar 8 23:27 rdisk0s1s1
crw-r----- 1 root operator 1, 3 Mar 8 23:27 rdisk0s1s2
crw-r----- 1 root operator 1, 4 Mar 8 23:31 rdisk1
crw-r----- 1 root operator 1, 5 Mar 8 23:38 rdisk2
crw-rw-rw- 1 root wheel 2, 0 Mar 8 23:39 tty
crw-rw-rw- 1 root wheel 7, 6 Mar 8 23:27 tty.bluetooth
crw-rw-rw- 1 root wheel 7, 4 Mar 8 23:27 tty.debug
crw-rw-rw- 1 root wheel 7, 2 Mar 8 23:27 tty.gas-gauge
crw-rw-rw- 1 root wheel 7, 0 Mar 8 23:27 tty.iap
crw-rw-rw- 1 root wheel 4, 0 Mar 8 23:27 ttyp0
crw-rw-rw- 1 root wheel 4, 1 Mar 8 23:27 ttyp1
crw-rw-rw- 1 root wheel 4, 2 Mar 8 23:27 ttyp2
crw-rw-rw- 1 root wheel 4, 3 Mar 8 23:27 ttyp3
crw-rw-rw- 1 root wheel 4, 4 Mar 8 23:27 ttyp4
crw-rw-rw- 1 root wheel 4, 5 Mar 8 23:27 ttyp5
crw-rw-rw- 1 root wheel 4, 6 Mar 8 23:27 ttyp6
crw-rw-rw- 1 root wheel 4, 7 Mar 8 23:27 ttyp7
crw-rw-rw- 1 root wheel 4, 8 Mar 8 23:27 ttyp8
crw-rw-rw- 1 root wheel 4, 9 Mar 8 23:27 ttyp9
crw-rw-rw- 1 root wheel 4, 10 Mar 8 23:27 ttypa
crw-rw-rw- 1 root wheel 4, 11 Mar 8 23:27 ttypb
crw-rw-rw- 1 root wheel 4, 12 Mar 8 23:27 ttypc
crw-rw-rw- 1 root wheel 4, 13 Mar 8 23:27 ttypd
crw-rw-rw- 1 root wheel 4, 14 Mar 8 23:27 ttype
crw-rw-rw- 1 root wheel 4, 15 Mar 8 23:27 ttypf
crw--w---- 1 mobile tty 16, 0 Mar 8 23:39 ttys000
crw-rw-rw- 1 root wheel 11, 3 Mar 8 23:27 uart.bluetooth
crw-rw-rw- 1 root wheel 11, 2 Mar 8 23:27 uart.debug
crw-rw-rw- 1 root wheel 11, 1 Mar 8 23:27 uart.gas-gauge
crw-rw-rw- 1 root wheel 11, 0 Mar 8 23:27 uart.iap
crw-rw-rw- 1 root wheel 10, 1 Mar 8 23:27 urandom
crw-rw-rw- 1 root wheel 3, 3 Mar 8 23:27 zero
iPhone-de-iFhone4s:/ root#

**Comment by iFhone4s** [comment]
Thanks for everything, i really need succesion, what a great job!

**Comment by Samgisaninja** [comment]
Please try again using the latest version of succession.

**Comment by Samgisaninja** [comment]
This was fixed in 1.4.13
