### ISSUE TITLE
Failed to remove old MSU directory (iPhone 5S, iOS 10.3.3, DH)

### ISSUE THREAD

**Issue by m1stadev** [Samgisaninja/SuccessionRestore#116]
With the latest version of Succession off of BigBoss (and also the latest version of Snappy off of Bingner's repo), I attempted to restore while also making an `orig-fs` snapshot. The only thing that seems to happen though, is an error that says Failed to remove old MSU directory. I did already delete the 12.4.5 update prior to running Succession.

[Log attached](https://github.com/Samgisaninja/SuccessionRestore/files/4356680/succession.log)

**Comment by m1stadev** [comment]
I restored the device again and tried running Succession (i'm running Succession for an orig-fs APFS snapshot) without removing the OTA update, and now I get this error:
`Failed to create /private/var/COPY/mnt1, You don't have permission to save the file "mnt1" in the folder "COPY".

[Log attached](https://github.com/Samgisaninja/SuccessionRestore/files/4356957/succession.log)

**Comment by cuikangyi** [comment]
same issue  with latest version
@M1staAwesome try the old version 1.3.x(or 1.4.7 maybe)，it work well on iPhone5s（10.3.3）

**Comment by Samgisaninja** [comment]
fixed by 6aaf005

**Comment by cuikangyi** [comment]
> fixed by 6aaf005

thanks 
i test it, there a new issue, the dir /var/mnt/succ can’t create in installing, i think the command should add “-p”
it works when i create the dir myself

**Comment by Samgisaninja** [comment]
yeah I figured that out but haven't pushed a new beta yet
