### ISSUE TITLE
What's the problem？

### ISSUE THREAD

**Issue by esf5021314** [Samgisaninja/SuccessionRestore#117]
![CCE194C5-A3AC-43D4-9E1D-6BBFCA3F1319](https://user-images.githubusercontent.com/29619019/77422861-243d9c80-6e09-11ea-8765-b25032bb822d.png)
What's the problem？How to deal with it?

**Comment by Samgisaninja** [comment]
can you send a log?

**Comment by Samgisaninja** [comment]
fixed by 6aaf005
