### ISSUE TITLE
Succession SoftwareUpdate

### ISSUE THREAD

**Issue by oneday95** [Samgisaninja/SuccessionRestore#119]
If you restore using Succession, the software cannot be updated.

**Comment by ashleyjcharman** [comment]
I thought that was generally the idea of Succession? 🙂

**Comment by demhademha** [comment]
Succession just restores your device to the current iOS version that your on, have you enabled “disable updates” in unc0ver by any chance?

**Comment by Samgisaninja** [comment]
^
