### ISSUE TITLE
Incolpatibility 

### ISSUE THREAD

**Issue by 7Iff5** [Samgisaninja/SuccessionRestore#121]
It says it is not compatible with unc0ver 40.-4.2.1 but I got unc0ver 4.3.1.
I got an iPhone XS Max under iOS 13.3

![1D56BC88-BC90-4C9F-85F7-E88C7760B8AC](https://user-images.githubusercontent.com/61103931/81486516-8f2a2200-9255-11ea-8c1e-08e38c1a6aae.png)
![4D2B1752-73ED-495A-BFC9-FD94F18C5F2F](https://user-images.githubusercontent.com/61103931/81486520-93563f80-9255-11ea-8df9-d0c1eabf55b5.png)

**Comment by Samgisaninja** [comment]
unfortunately my check for 4.2.X didn't account for users who upgraded from 4.2.X/lower without restoring roots. this was just fixed in 1.4.14, sorry about that
