### ISSUE TITLE
Thought this was a better option.

### ISSUE THREAD

**Issue by biggv** [Samgisaninja/SuccessionRestore#122]
Yeah, used Cydia Eraser about a year ago with no issue.  Now i needed to restore again and was told this was the better option .  Downloaded it and startetd from the IPSW that it downloaded.  While going it says that sometimes it will freeze and that it will just continue so leave it be until it rreboots.  Well my issue started 11pm when i hit start, now it is 9:25am and im still on "Restoring System\Library\Caches\com.apple.dyld\dyld_shared_cache_armv7s\

I put the phone in lock so it could cool down, ~9am, and once unlocked again it starts heating up again.  It has been 10+hours man, tf am i supposed to do now?
ios 10.3.2, latest version of succession.

**Comment by biggv** [comment]
ios 10.3.2, latest version of Succession that said there was an update last night.

**Comment by biggv** [comment]
new issue, unlocked the phone and was on homescreen.  Succession crashed.  Cant open any app now :D

**Comment by Samgisaninja** [comment]
one of two things happened:

1. your device ran out of storage mid-way through
2. when you locked it to "let it cool", iOS killed succession

neither of these are bugs with succession, so this is therefore closed. given that it's a 32-bit device, you should probably restore with iTunes.

**Comment by biggv** [comment]
the whole point of using succeession was to avoid the forced update.  Also how did locking it after NINE HOURS kill the process.  The device still had 5gb free after downloading the ipsw

**Comment by biggv** [comment]
the device worked better after it was restarted.  Functioned like normal.  Went and rejailbroke, ran succession on erase data only.  Went through the process, reached a point where it popped up saying restoring the icons.  Then popped to a black screen.  What should be expected or done at this point?
