### ISSUE TITLE
No app on the homescreen

### ISSUE THREAD

**Issue by mastercreeper66** [Samgisaninja/SuccessionRestore#123]
Hi, i have an iPhone 4S on iOS 8.4.1 jailbroken with EtaSon JB, i installed succession from BigBoss but nothing appears on the homescreen. i already ran the uicache command

**Comment by Samgisaninja** [comment]
can you please reinstall succession and screenshot the Cydia output

(also I seem to remember that etasonjb had a problem with icons disappearing, perhaps try home depot)

**Comment by mastercreeper66** [comment]
![2020-05-14 18 59 30](https://user-images.githubusercontent.com/31628599/81963243-222bd900-9615-11ea-98f3-2091c8dd43e6.jpg)

**Comment by Samgisaninja** [comment]
alright, welp, no errors on install.

After having researched a little further, this is a known issue with the etasonJB jailbreak. Unfortunately that means that I can't fix it as it's not a problem with Succession. Sorry about that.

**Comment by mastercreeper66** [comment]
I noticed that there's no executable in the succession's app folder. There's an executable named "SuccessionRestore_", i tried to remove the "_" from the name, ran uicache and an app appeared on the homescreen but it instantly closes.

**Comment by Samgisaninja** [comment]
Now *that* is interesting, there may be a postinst issue. Reopened, I'll look into it tomorrow

EDIT: ok, wow, I didn't realize how big of a mess the postinst was...

**Comment by Samgisaninja** [comment]
just figured I'd post an update, I've purchased an iPhone 4s, reproduced issue.

**Comment by demhademha** [comment]
Hi @mastercreeper66  would you be willing to test something for us?

**Comment by mastercreeper66** [comment]
Sure!

**Comment by Samgisaninja** [comment]
Fixed in 1.4.15
