### ISSUE TITLE
Only restore system data or full wipe?

### ISSUE THREAD

**Issue by 3xtazzy** [Samgisaninja/SuccessionRestore#125]
Hello there,

I’m confused which option is the best for my condition, so I want to play a game but it requires me to be un-jailbroken I tried every bypass tweak but none of them are working.

Should I use only restore system data or full wipe? I will backup my data first before doing this

**Comment by demhademha** [comment]
Just use SnapBack, no need to use succession

**Comment by 3xtazzy** [comment]
> Just use SnapBack, no need to use succession

I tried it before the game still detects that I was jailbroken before 
(https://c-notification.klabgames.com/? Error 32 The app has been shut down because one or more prohibited actions were detected.

Are you using a jailbroken device? This app does not boot or run properly on a device that has been jailbroken even once.)

but worth it to try it again, and checkra1n have issue about re-jailbreaking (I need to remove the jailbreak first)

**Comment by demhademha** [comment]
In your case then, I’d restore full system

**Comment by 3xtazzy** [comment]
> In your case then, I’d restore full system

Do you mean by wiping my phone with Succession?

**Comment by demhademha** [comment]
Yes

**Comment by Samgisaninja** [comment]
This is a bug tracker, not a support forum.
