### ISSUE TITLE
iPhone 6

### ISSUE THREAD

**Issue by mohammed2008we** [Samgisaninja/SuccessionRestore#129]
Hello 
iPhone 6 iOS 12.4.4 I want to downgrade to iOS 10 stuck in attach 
[SUCCESSIONLOG 1.4.14: 2020-05-31 16:00:21 +0000] Line 92: Mountpoint exists, continuing
[SUCCESSIONLOG 1.4.14: 2020-05-31 16:00:21 +0000] Line 134: attachDiskImage called!
[SUCCESSIONLOG 1.4.14: 2020-05-31 16:00:21 +0000] Line 137: using hdik to attach disk image
[SUCCESSIONLOG 1.4.14: 2020-05-31 16:00:21 +0000] Line 142: /Applications/SuccessionRestore.app/succdatroot /Applications/SuccessionRestore.app/hdik /private/var/mobile/Media/Succession/rfs.dmg
[SUCCESSIONLOG 1.4.14: 2020-05-31 16:00:21 +0000] Line 150: hdik completed with
hdik: attach failed: error 0x6e = 110

[SUCCESSIONLOG 1.4.14: 2020-05-31 16:00:21 +0000] Line 207: changedDevContents:

**Comment by demhademha** [comment]
Succession isn’t intended for that.
You can only restore to the current version and besides, SEP  would probably be incompatible
