### ISSUE TITLE
iPhone 6

### ISSUE THREAD

**Issue by mohammed2008we** [Samgisaninja/SuccessionRestore#131]
iOS 12 to iOS 10
Can’t restore system file system isn’t mounted 
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:13 +0000] Line 602: Extracting DMG, 32768 bytes extracted, 494370816.000000 of 9300257586450268160.000000 total
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:13 +0000] Line 602: Extracting DMG, 32768 bytes extracted, 494403584.000000 of 9300257586450268160.000000 total
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:13 +0000] Line 602: Extracting DMG, 32768 bytes extracted, 494436352.000000 of 9300257586450268160.000000 total
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 92: Mountpoint exists, continuing
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 134: attachDiskImage called!
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 137: using hdik to attach disk image
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 142: /Applications/SuccessionRestore.app/succdatroot /Applications/SuccessionRestore.app/hdik /private/var/mobile/Media/Succession/rfs.dmg
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 150: hdik completed with
/dev/disk36         	GUID_partition_scheme          	
/dev/disk36s1       	C12A7328-F81F-11D2-BA4B-00A0C93	
/dev/disk36s2       	48465300-0000-11AA-AA11-0030654	

[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 153: /dev/disk36         	GUID_partition_scheme          	,
/dev/disk36s1       	C12A7328-F81F-11D2-BA4B-00A0C93	,
/dev/disk36s2       	48465300-0000-11AA-AA11-0030654	,

[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 154: outlines count: 4
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 157: current line is /dev/disk36         	GUID_partition_scheme          	
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 157: current line is /dev/disk36s1       	C12A7328-F81F-11D2-BA4B-00A0C93	
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 157: current line is /dev/disk36s2       	48465300-0000-11AA-AA11-0030654	
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 159: found attached diskpath in /dev/disk36s2       	48465300-0000-11AA-AA11-0030654	
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 163: found attached diskpath /dev/disk36s2
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 308: prepareMountAttachedDisk called!
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 316: Identified filesystem as APFS!
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 157: current line is 
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:18 +0000] Line 345: mounting complete! 
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:21 +0000] Line 362: tappedRestoreButton called
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:21 +0000] Line 405: no apfs snapshot operations requested
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:21 +0000] Line 411: showRestoreAlert called!
[SUCCESSIONLOG 1.4.14: 2020-05-31 20:01:21 +0000] Line 472: ERROR!  Can't restore, filesystem isn't mounted.

**Comment by demhademha** [comment]
... are you still trying to downgrade to ios 10 from 12?

**Comment by mohammed2008we** [comment]
Yes

> ... are you still trying to downgrade to ios 10 from 12?
Yes

**Comment by demhademha** [comment]
WHAT PART OF YOU CAN NOT DO THAT DO YOU NOT UNDERSTAND?

**Comment by mohammed2008we** [comment]
> WHAT PART OF YOU CAN NOT DO THAT DO YOU NOT UNDERSTAND?

Ok bro understand
