### ISSUE TITLE
Device turns off when booting after restore

### ISSUE THREAD

**Issue by mastercreeper66** [Samgisaninja/SuccessionRestore#134]
I restored my iPhone 4S on iOS 8.4.1, but when it rebooted it got stuck in the apple logo with the progress bar, i waited for like an hour but nothing happened, i rebooted the device and the apple logo appeared for 50 seconds and then it turned off. 
if i try to turn it on again, the same thing happens

**Comment by Samgisaninja** [comment]
Just tested this on my iPhone 4s, was unable to reproduce. I recommend following this guide: https://www.youtube.com/watch?v=fh0tB6fp0Sc
