### ISSUE TITLE
What is     if (sizeof(void *) != 4) { in line 136 at RestoreViewController.m mean?

### ISSUE THREAD

**Issue by kocoman1** [Samgisaninja/SuccessionRestore#136]
For some reason hdik is not working on the ios9 device, some error 0x..... that you said was fixed but for me was not.  

I am trying to use attach instead without recompiling 

What is     if (sizeof(void *) != 4) { in line 136 at RestoreViewController.m mean?

thanks

**Comment by Samgisaninja** [comment]
sizeof(void *) will return 4 on 32-bit devices.
