### ISSUE TITLE
The succdatroot is not supported in ios 9.3.3 with pangu jailbreak because the dylib does not exist

### ISSUE THREAD

**Issue by kocoman1** [Samgisaninja/SuccessionRestore#137]

**Comment by Oakman312** [comment]
I am having the same issue here on an iPhone 6 on iOS 9.3.2. Succession immediately crashes when I try to open it.

**Comment by kocoman1** [comment]
Dont restore you will get stuck at activation screen

**Comment by Samgisaninja** [comment]
Duplicate of #133
