### ISSUE TITLE
Help Me succession can't restore filesystem isn't mounted

### ISSUE THREAD

**Issue by Falcon0326** [Samgisaninja/SuccessionRestore#138]
Help Me 
iPhone7 IOS 10.1.1
I want  Update Succession IOS 11.0.1
succession can't restore filesystem isn't mounted error

Help　Please
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/5312371/succession.log)

**Comment by demhademha** [comment]
Succession is intended to only restore to the same ios version that  you are currently on, it can't be used like that.

**Comment by Falcon0326** [comment]
> Succession is intended to only restore to the same ios version that you are currently on, it can't be used like that.

Thank you 
This iPhone　ios 10.1.1
I think so version update .
But I want to jailbreak.
Help me

**Comment by demhademha** [comment]
https://checkra.in will work on your device if/when checkra1n is updated however, this isn't a jailbreak forum / support.
