### ISSUE TITLE
Error 44

### ISSUE THREAD

**Issue by cutehairboy** [Samgisaninja/SuccessionRestore#139]
I want to Restore **iOS 11.3** iPSW File on SuccessionDown on my **iPhone 6**. But I get this error: Succession has failed due to an issue with rsync. I don’t know what caused this, sorry. You can follow the discussion of this issue at https://github.com/SuccessionRestore/issues **44**. Please help me asap. Note: My iPhone 6 is on iOS 12.4.8

**Comment by demhademha** [comment]
Succession isn't designed to allow you to downgrade. It allows you to only restore to the same version that your currently on, in your case, to 12.4.8.

**Comment by cutehairboy** [comment]
> Succession isn't designed to allow you to downgrade. It allows you to only restore to the same version that your currently on, in your case, to 12.4.8. 

How? It was completed successfully when I did it before on iOS 12.4.7 on my iPhone 6. [11.3 iPSW] But at that time I don't have a Mac and can't booted with pyboot.

**Comment by Samgisaninja** [comment]
Please report all issues with SuccessionDown to https://github.com/MatthewPierson/Divise/issues
