### ISSUE TITLE
Succession crashes on iPhone 6 running iOS 9.3.3

### ISSUE THREAD

**Issue by Meowmycks** [Samgisaninja/SuccessionRestore#143]
Hello, I have a jailbroken iPhone 6 running iOS 9.3.3 and I am trying to use your Succession app to restore it. However, it doesn't work for me.

When trying to open the Succession app from the home screen, it only crashes. Restarting my phone does not help and reinstalling the app didn't work either.

What can I do to fix this and/or what information do you need from me to be able to help you?

Thank you.

**Comment by Samgisaninja** [comment]
Duplicate of #133

**Comment by Anonzie** [comment]
Were you able to fix it?
