### ISSUE TITLE
Stuck at: Attaching... This should take less than 10 seconds.

### ISSUE THREAD

**Issue by ishansahni** [Samgisaninja/SuccessionRestore#148]
I'm on iPhone 12 Pro Max | iOS 14.3 |

This is the error log: 
(please help me)

[SUCCESSIONLOG 1.4.15: 2021-04-28 14:41:11 +0000] Line 92: Mountpoint exists, continuing
[SUCCESSIONLOG 1.4.15: 2021-04-28 14:41:11 +0000] Line 134: attachDiskImage called!
[SUCCESSIONLOG 1.4.15: 2021-04-28 14:41:11 +0000] Line 137: using hdik to attach disk image
[SUCCESSIONLOG 1.4.15: 2021-04-28 14:41:11 +0000] Line 142: /Applications/SuccessionRestore.app/succdatroot /Applications/SuccessionRestore.app/hdik /private/var/mobile/Media/Succession/rfs.dmg
[SUCCESSIONLOG 1.4.15: 2021-04-28 14:41:11 +0000] Line 150: hdik completed with
hdik: attach failed: error 0xe00002e2 = -536870174

[SUCCESSIONLOG 1.4.15: 2021-04-28 14:41:11 +0000] Line 207: changedDevContents:

**Comment by remonvn** [comment]
I got the exact same error. @ishansahni how did you fix this?

**Comment by ishansahni** [comment]
> I got the exact same error. @ishansahni how did you fix this?

I did manage to fix it use this it's the beta version 

https://sharerepo.stkc.win/?repo=https://samgisaninja.github.io/test/
