### ISSUE TITLE
Invisible Restore Button on Succession v1.1.1

### ISSUE THREAD

**Issue by jluo98** [Samgisaninja/SuccessionRestore#18]
Just tried to restore my iPhone X on 12.1.1. I noticed that the "restore" button is invisible on the warning page, but it can still be activated by tapping the bottom of the screen. 

Other than this small UI bug, the download and restore process were successful. 

![Screenshot](https://user-images.githubusercontent.com/8736917/56620748-9a30f680-65ef-11e9-88d5-72095ad88eb7.png)

**Comment by Samgisaninja** [comment]
Fixed in 1.2.4
