### ISSUE TITLE
[Feature Request]: Creation of a background process(daemon)

### ISSUE THREAD

**Issue by Itamiko** [Samgisaninja/SuccessionRestore#20]
When downloading an ipsw would like to exit the application and do other things(watch youtube) while it's being downloaded, could have the application create a daemon service for background processes then push notification on successful download event or something like that.

**Comment by Samgisaninja** [comment]
I'll look into it, IDK if I'll use that exact implementation, but background downloads is an interesting idea

**Comment by Samgisaninja** [comment]
I’ve kinda re-thought this, no. 

I don’t want to encourage people trying to "do other things" on their device while this is running. It’s a delicate process, and I don’t want someone’s clash of clans to hog memory and crash this while it’s running. Succession clearly states “do not leave the app”, this is for a reason.
