### ISSUE TITLE
Possible to also UPDATE to unsigned versions that are higher?

### ISSUE THREAD

**Issue by Macleykun** [Samgisaninja/SuccessionRestore#22]
Hey I recently found your tweak and wonders if for A12 it would be possible to also update from like 12.0.1 to like 12.1.2.

I had blobs they are invalid bc i didn’t knew I had to add my own appnonces.

Hope to hear from you soon! I’m impressed by your work!

**Comment by yp261** [comment]
it's impossible.

**Comment by Samgisaninja** [comment]
No
