### ISSUE TITLE
Thx bootlooped my 6s+ 

### ISSUE THREAD

**Issue by Kai0KenX20** [Samgisaninja/SuccessionRestore#24]
Just wanted to say thanks after INSTALLING only I attempted to open it and bam Respring and infinite bootloop so thanks for making all my money wasted on the tweaks and donations I’ve gave was forced to update to 12.2 so yeah thx

**Comment by Samgisaninja** [comment]
1a62a8f

**Comment by Itamiko** [comment]
is this fixed?

**Comment by Samgisaninja** [comment]
Yes
