### ISSUE TITLE
Pressing Erase iPhone doesn’t start the restoration

### ISSUE THREAD

**Issue by kienhho** [Samgisaninja/SuccessionRestore#25]
Version: 16C5050a - 12.1.1b3
Device: iPad8,3
Jailbreak: Chimera 1.0.4
Succession Version: 1.2.4
IPSW: Local
Bug: Pressing Erase iPhone doesn’t start the restoration

What have I tried so far?
Try rebooting
Downgrade to an earlier version (on my other device with unc0ver, I tried 1.1.6 and 1.2 and only 1.1.6 works, so the bug started in 1.2)

The story:
I pressed Erase iPhone (at the bottom), then it an alert said “ Mounting Filesystem... “. Then I pressed OK and it still stays in the Erase iPhone screen, not doing anything.
I can’t downgrade to 1.1.6 because it doesn’t support A12X/Chimera. I don’t want to use Restore rootFS because I want to cleanly wipe my iPad.

**Comment by Samgisaninja** [comment]
can you please:
1. reboot
2. run `ls /dev >> /var/mobile/Media/dev.txt` in terminal
3. try to restore, let it fail
4. run `ls /dev >> /var/mobile/Media/dev.txt` in terminal again

**Comment by ghost** [comment]
Same problem with iPad5,1 (12.1.1) on uncover 3.0.1.

**Comment by Samgisaninja** [comment]
[can confirm](https://i.imgur.com/XjNKfQk.jpg)

**Comment by Samgisaninja** [comment]
*sigh*

tfw you spell "exclude" wrong

639519e
