### ISSUE TITLE
Attach failed

### ISSUE THREAD

**Issue by Multipixelone** [Samgisaninja/SuccessionRestore#26]
I've looked everywhere for an answer to this. My phone has been having issues so I wanted to restore it.

I have an iPhone 7+ On 12.1.2 jailbroken with u0 3.0.1, and I am using Succession 1.2.4. After downloading the IPSW, when I go to restore my iPhone it says, "Attach failed, exit code 5 (hopefully his will never happen because I will have no clue how to debug it)."

**Comment by Samgisaninja** [comment]
This issue is resolved in succession 1.3, which will be released as soon as I can confirm it works on A12
