### ISSUE TITLE
Can't erase my iPad 4,2 - iOS ver.: 12.0.1 - iOS Build: 16A404

### ISSUE THREAD

**Issue by ar1s3** [Samgisaninja/SuccessionRestore#31]
I've an iPad 4,2 with iOS 12.0.1 and Succession updated to latest version (1.3.2). I tried to download custom ipsw and downloading it from the Succession itself; in both of cases when i click on "Erase iPhone", a popup message showup telling me "Mounting Filesystem - This step might fail..." and it fail.
I tried many many time rebooting the device, but the same result happen everytime, even trying to re-jailbreak and uninstalling and re-installing succession itself.

Could you please help me understanding what's is wrong or where i'm wrong?

Regards.

**Comment by Samgisaninja** [comment]
duplicate of #28 -- please direct all discussion there
