### ISSUE TITLE
Nothing Happens like #32

### ISSUE THREAD

**Issue by TomKFL** [Samgisaninja/SuccessionRestore#33]
iPhone 11,6; A12; iOS 12.0; Build 16A366; Sucession Version 1.3.1
Button after IPSW Download does nothing tried rebooting 2h or so but no chance...

**Comment by TomKFL** [comment]
Succession created no log at all

**Comment by eeverywheree** [comment]
Same here on an iPhone 10,6 / 12.1.1b3 (16C5050a) and on an iPad 7,5 / 12.1.1b3 (16C5050a), it does nothing when I press "Erase iPhone", just showing "Mouting Filesystem" and when I click ok, nothing happens.

**Comment by Samgisaninja** [comment]
Duplicate of #28
