### ISSUE TITLE
Erase iPhone not working

### ISSUE THREAD

**Issue by Antraxs** [Samgisaninja/SuccessionRestore#35]
Trying to restore my iPhone but nothing happens when I press “Erase iPhone”. Rebooted multiple time and even downloaded the ipsw.

iPhone 11,6 
iOS 12.1.1
iOS Build 16C50

**Comment by Samgisaninja** [comment]
does /var/MobileSoftwareUpdate/mnt1/sbin/launchd exist?

**Comment by Antraxs** [comment]
/sbin/launchd does not exist

**Comment by Antraxs** [comment]
totally blanked out but nothing happened when the "Mounting filesystem" popup comes up.

**Comment by Samgisaninja** [comment]
Duplicate of #28
