### ISSUE TITLE
Identifying rootfilesystem dmg - iOS 12.0.1 - iPhone 6S

### ISSUE THREAD

**Issue by ar1s3** [Samgisaninja/SuccessionRestore#40]
Hi man,
after downloading the .ipsw file of iOS 12.0.1 and put in the Succession folder, i start the unzipping process but after very very long time i saw that's stucked on "Identifying rootfilesystem dmg".

I've successfully installed, recently, the latest version of Succession.

Could you please help me understanding what's happening and how to solve that?

Regards

**Comment by Samgisaninja** [comment]
Fixed in fe8e6e477c2c5cb80b47051a0ebc659019103bc8

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
