### ISSUE TITLE
Finding ipsw issue

### ISSUE THREAD

**Issue by jackng80** [Samgisaninja/SuccessionRestore#42]
![92CDCDCD-F8B9-4DB2-A18D-20D372FDEE17](https://user-images.githubusercontent.com/52749808/60975160-ae1a0800-a355-11e9-9155-f7d4082873c5.jpeg)

**Comment by Samgisaninja** [comment]
yeah-- I just saw this on reddit, can you please provide your iOS build number and device model as listed on succession's homepage?

**Comment by jackng80** [comment]
I'm using iphone XS, ios 12.1

**Comment by Samgisaninja** [comment]
api.ipsw.me went down

https://api.ipsw.me/iPhone11,2/16B92/url/ 

This is not an issue with Succession, and there's nothing I can do about this.
