### ISSUE TITLE
Mouting system

### ISSUE THREAD

**Issue by sonhl0105** [Samgisaninja/SuccessionRestore#48]
I have error with new version 1.3.5 on 6s+ and ios 12.0. Help me pls :(

https://www.dropbox.com/sh/vrwdr0ssvqk1b9p/AAC9jBA3n2i-knrEYsdLBV3Da?dl=0

**Comment by sonhl0105** [comment]
I’m so sorry because I’m using mobile so I can’t upload image error

**Comment by sonhl0105** [comment]
Hi @Samgisaninja. I need your help :(

**Comment by maxshcherbina** [comment]
1.3.4 seemed to work fine for me, so if anyone is having trouble with 1.3.5, try that.

**Comment by sonhl0105** [comment]
> 1.3.4 seemed to work fine for me, so if anyone is having trouble with 1.3.5, try that.

It's work. Thanks @darendark so much.

**Comment by PanicAttac** [comment]
I’m trying to use Succession version 1.37 on my iPhone 8 Plus iOS 12.4. I can get up to the point where it says erase iPhone at the bottom, then a pop up comes up saying mounting file system press ok and nothing happens 

Please help as I need to get rid of the jailbreak to get my phone repaired

**Comment by maxshcherbina** [comment]
@PanicAttac read my comment ^

**Comment by Samgisaninja** [comment]
1.3.4 unfortunately has #37, which will produce the same results (for some people)

**Comment by mclopes** [comment]
@samgisaninja you referenced this issue from mine but after reading it I’m still not sure on the steps to take. 

Do I follow the instructions on #37 ?

**Comment by Samgisaninja** [comment]
@mclopes tbh there's not much you can do, it's something I have to fix.

Hopefully 9ebc54d did just that, but I don't know and I am not prepared to release a beta yet.

**Comment by Samgisaninja** [comment]
This has been fixed in succession 1.4.2
