### ISSUE TITLE
Crashing upon clicking "Prepare for restore!"

### ISSUE THREAD

**Issue by Infinitay** [Samgisaninja/SuccessionRestore#51]
Device information: iPhone 5s (iPhone6,1) on iOS 10.2 (Build 14C92)
I am using Succession v1.3.5 from the BigBoss repo

At first I didn't have enough space when I was downloading the IPSW, so I freed some space up and removed contents inside var/mobile/media/Succession.

Afterwards, my app crashed when it was attempting to unzip the IPSW so I gave up letting the app handle it and I manually extracted the DMG file myself. What I did was download the respective IPSW and used TransMac to retrieve the DMG. I followed instructions I found on Reddit that said to open the IPSW and find pull the largest DMG file within, and open it with TransMac and expand (extract) that. Then I transferred it to my device and tried restoring once more.

As the title says, when I click "Prepare to restore!", my app immediately crashes, and there is nothing helpful within my logs.

Logs:

> [SUCCESSIONLOG 1.3.5: 2019-08-20 04:30:42 +0000] Line 27: RestoreViewController has loaded!

I should note that my device no longer has access to my carrier's network as I have a new phone. When I activated the new one, the sim on my old phone automatically stopped working, so i never bothered taking it out. I did try running Succession on airplane mode and that didn't help

**Comment by Samgisaninja** [comment]
I think this might be fixed in 1.3.6, I remember having this issue not too long ago but I thought it was contained to the beta builds. Either way, I remember getting it to work, I don't remember if I actually fixed it or if it just started working out of the blue.

Can you please add my repository, https://samgisaninja.github.io/ and install succession 1.3.6?

**Comment by Infinitay** [comment]
Thank you very much! It didn't crash this time when I clicked on "Prepare for restore!"

I am currently running the restore with the low-storage option that was prompted to me.

Edit: Successfully restored, I blue screened and thought something went wrong but all is fine, thank you again.

**Comment by Samgisaninja** [comment]
Cool, yeah the blue screen is "normal" (that's apple's fault). Glad it worked for ya!
