### ISSUE TITLE
Succession 1.3.4 hangs on usr/share

### ISSUE THREAD

**Issue by m1stadev** [Samgisaninja/SuccessionRestore#54]
No matter how many times I try to run it, it’ll always freeze there. I’ve left it overnight with no success. I’ve tried to use 1.3.7, but I still get the Mounting Filesystem information. iPhone 5S, iOS 10.3.3. If I hard reboot (probably not the best thing to do but it’s either reboot or leave it at that), then my installed apps will all crash upon launch and not work (defaults still work). Sideloading and jailbreaking my device again works fine, but if I try to run Succession then this happens again

**Comment by m1stadev** [comment]
I’ll leave it running overnight just incase anything changes

**Comment by Samgisaninja** [comment]
if you could post a log, that'd be much appreciated, I have a sneaking suspicion that this is a duplicate of #44, but a log would let me know for sure

**Comment by m1stadev** [comment]
Trying it again. Once it freezes up i’ll hard reset, rejb and get filza, and grab the log

**Comment by m1stadev** [comment]
Aaaaaand of course I run it the second time and it actually works. Don’t have a log for when I had the issue, so I’ll just close this.

**Comment by m1stadev** [comment]
Restored successfully now, but it did nothing. Dupe of #44 I guess. Will post log there.
