### ISSUE TITLE
Ios10 Meridian越狱平刷问题?

### ISSUE THREAD

**Issue by luohui201988** [Samgisaninja/SuccessionRestore#55]
所有ios10-10.3.3系统 Meridian越狱的 用SuccessionRestore平刷 刷完重起 数据还在 没有抹去是什么原因呢？

**Comment by Samgisaninja** [comment]
重复的 #44 

(用谷歌翻译)

**Comment by luohui201988** [comment]
不是哦 我刚越狱的 什么插件都没有安装 也没有在icleaner pro禁用什么  这个问题你测试过吗

**Comment by luohui201988** [comment]
> 重复的[＃44](https://github.com/Samgisaninja/SuccessionRestore/issues/44)
> 不是哦我刚越狱的什么插件都没有安装也没有在icleaner pro禁用什么这个问题你测试过吗
> （用谷歌翻译）
