### ISSUE TITLE
restore not starting.

### ISSUE THREAD

**Issue by gbm777** [Samgisaninja/SuccessionRestore#57]
![4F24568C-D8F8-41CE-85CF-974517D2E175](https://user-images.githubusercontent.com/35556952/64059234-aa369380-cbea-11e9-9bec-47dace851321.png)

wts wrong with ios 12.4 iphone 6

**Comment by Samgisaninja** [comment]
Duplicate of #48

**Comment by gbm777** [comment]
btw im using newest 1.3.8version
