### ISSUE TITLE
Pls help iPhone 8 I’m on iOS 12.4 unc0ver jb

### ISSUE THREAD

**Issue by mudi47** [Samgisaninja/SuccessionRestore#59]
![3E8F2170-ED6E-41FA-9578-C493D8F29681](https://user-images.githubusercontent.com/53701264/64129153-aeb1a680-cdba-11e9-80be-8413f21aae79.jpeg)
![BEC45F0E-B045-498E-BB56-1AAD733458EC](https://user-images.githubusercontent.com/53701264/64129154-aeb1a680-cdba-11e9-9252-43d2b2fd41e6.jpeg)

**Comment by Samgisaninja** [comment]
Duplicate of #48

**Comment by mudi47** [comment]
I fixed it bro thx❤️
