### ISSUE TITLE
Crash and recede in the final step of recovery A12 xsmax 12.1.1 chimera 

### ISSUE THREAD

**Issue by jfjjjdi** [Samgisaninja/SuccessionRestore#60]
In the final step of recovery crash flashback, he didn't clean the desktop icon and reboot for me he didn't perform uicache -a
I've tried many times to flash back in the last step of cleaning the cache, without cleaning the icon and restarting the device. 
[succession.log](https://www.dropbox.com/s/zgu56ag8s9aqg6l/succession.log?dl=0)

**Comment by Samgisaninja** [comment]
hmm, can you please go to /var/mobile/Library/CrashReporter/ and see if there are any succession-related logs?

**Comment by jfjjjdi** [comment]
There is no relevant log, I use cr4shed

**Comment by Samgisaninja** [comment]
Please check the folder.

**Comment by jfjjjdi** [comment]
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/3582525/succession.log)

![1BC523EC-7744-41BD-8B43-F0332622707C](https://user-images.githubusercontent.com/32479431/64407288-92fa1900-d0b6-11e9-9a7b-78829d54e7a2.png)

I checked, only the logs generated on succession

**Comment by jfjjjdi** [comment]
> Please check the folder.

![213EB8C5-985D-4256-94AB-1A4A5314F52B](https://user-images.githubusercontent.com/32479431/64407470-f6844680-d0b6-11e9-8ba6-ffdbce50998d.jpeg)
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/3582536/succession.log)

I checked, only the logs generated on succession.
