### ISSUE TITLE
Stuck at update ramdisk

### ISSUE THREAD

**Issue by BiOh424rD** [Samgisaninja/SuccessionRestore#64]
IPhone XS 256Gb iOS 12.2 Unc0ver 3.7.0~b1 Succession 1.3.8 (already tried other previous versions like the 1.3.4) 

The restore still stuck at 👍

> [SUCCESSIONLOG 1.3.8: 2019-09-25 13:43:58 +0000] Line 472: usr/standalone/firmware/nfrestore/firmware/
> usr/standalone/firmware/nfrestore/firmware/fw/
> usr/standalone/firmware/oscar/
> usr/standalone/update/
> usr/standalone/update/all_flash/
> usr/standalone/update/

And do nothing for hours.
Full pre digest 

> [SUCCESSIONLOG 1.3.8: 2019-09-25 13:43:58 +0000] Line 472: usr/libexec/Library/Preferences/Logging/
> usr/libexec/Library/Preferences/Logging/Subsystems/
> usr/libexec/dtrace/
> usr/sbin/
> usr/sbin/WiFiNetworkStoreModel.momd/
> usr/share/
> usr/share/CSI/
> usr/share/com.apple.languageassetd/
> usr/share/firmware/
> usr/share/firmware/bluetooth/
> usr/share/firmware/wifi/
> usr/share/firmware/wifi/C-4377__s-B1/
> usr/share/firmware/wifi/C-4377__s-B2/
> usr/share/icu/
> usr/share/langid/
> usr/share/locale/
> usr/share/locale/UTF-8/
> usr/share/mecabra/
> usr/share/mecabra/common/
> usr/share/mecabra/common/descriptions/
> usr/share/mecabra/common/descriptions/JapaneseBigram.momd/
> usr/share/mecabra/common/descriptions/LearningDictionary.momd/
> usr/share/mecabra/common/descriptions/LearningDictionaryJapanese.momd/
> usr/share/misc/
> usr/share/progressui/
> usr/share/progressui/images-2x/
> usr/share/tokenizer/
> usr/share/tokenizer/ja/
> usr/share/tokenizer/ko/
> usr/share/tokenizer/zh/
> usr/share/tokenizer/zh/Hans/
> usr/share/tokenizer/zh/Hant/
> usr/share/zoneinfo.default/
> usr/share/zoneinfo.default/Africa/
> usr/share/zoneinfo.default/America/
> usr/share/zoneinfo.default/America/Argentina/
> usr/share/zoneinfo.default/America/Indiana/
> 
> [SUCCESSIONLOG 1.3.8: 2019-09-25 13:43:58 +0000] Line 472: usr/share/zoneinfo.default/America/Kentucky/
> usr/share/zoneinfo.default/America/North_Dakota/
> usr/share/zoneinfo.default/Antarctica/
> usr/share/zoneinfo.default/Arctic/
> usr/share/zoneinfo.default/Asia/
> usr/share/zoneinfo.default/Atlantic/
> usr/share/zoneinfo.default/Australia/
> usr/share/zoneinfo.default/Brazil/
> usr/share/zoneinfo.default/Canada/
> usr/share/zoneinfo.default/Chile/
> usr/share/zoneinfo.default/Etc/
> usr/share/zoneinfo.default/Europe/
> 
> [SUCCESSIONLOG 1.3.8: 2019-09-25 13:43:58 +0000] Line 472: usr/share/zoneinfo.default/Indian/
> usr/share/zoneinfo.default/Mexico/
> usr/share/zoneinfo.default/Pacific/
> usr/share/zoneinfo.default/US/
> usr/standalone/
> usr/standalone/firmware/
> usr/standalone/firmware/nfrestore/
> 
> [SUCCESSIONLOG 1.3.8: 2019-09-25 13:43:58 +0000] Line 472: usr/standalone/firmware/nfrestore/firmware/
> usr/standalone/firmware/nfrestore/firmware/fw/
> usr/standalone/firmware/oscar/

> usr/standalone/update/
> usr/standalone/update/all_flash/
> usr/standalone/update/ramdisk/

**Comment by Samgisaninja** [comment]
This is an issue with rsync. SnapBack has the same problem. 

I'll put out an MOTD about this.

**Comment by Samgisaninja** [comment]
confirmed that the above commit has resolved this issue, will close upon 1.4's release, eta son(tm)

**Comment by ghost** [comment]
Thx

**Comment by secret223** [comment]
Then
