### ISSUE TITLE
1.4 on A12 Crash at Mount.

### ISSUE THREAD

**Issue by BiOh424rD** [Samgisaninja/SuccessionRestore#66]
https://github.com/Samgisaninja/SuccessionRestore/issues/64
Same device.
After updating succession, on 1.4 when I start restore, after the pop up that say mounting disk ecc kernel always panic and device reboot.
No log in /var.
iOS 12.2 iPhone XS 254 Gb unc0ver b~1

**Comment by Samgisaninja** [comment]
Duplicate of #48
