### ISSUE TITLE
A12 panic when beginning restore

### ISSUE THREAD

**Issue by Samgisaninja** [Samgisaninja/SuccessionRestore#67]
Opened because of user reports. If anyone could please run this while connected to idevicesyslog, that'd be really helpful.

**Comment by BiOh424rD** [comment]
I want but you disabled the 1.4 app access ...

**Comment by Samgisaninja** [comment]
if you enable airplane mode, then tap "download a filesystem", then disable airplane mode, then start the download, the block will be bypassed.

If you choose to restore while connected to idevicesyslog, I'd really appreciate it, but given that there have been reports of bootloops, don't feel any obligation to do so.

**Comment by Samgisaninja** [comment]
@BiOh424rD do you have discord?

**Comment by BiOh424rD** [comment]
> Resilienza#4705

I’ll try when return to home

**Comment by BiOh424rD** [comment]
https://justpaste.it/7sdml
i'll try with 100% battery soon.

**Comment by Samgisaninja** [comment]
Sorry, should've asked the first time, but can you also enable "log output to /var/mobile/succession.log" in settings (you don't need to send me the file, but this will make succession's logs visible in the syslog)

Just curious, did you get the "You should have 50% battery" alert, or did the device reboot before that alert?

**Comment by BiOh424rD** [comment]
No battery alert...
Now battery is fully charged.
idevicesyslog and device panic log.
https://1drv.ms/u/s!Aot6ho0srLCcgeRmSKwvm5EvOTgwog?e=dHmVdb
No Succession.log written (?) i'll try yet..

**Comment by Samgisaninja** [comment]
Thanks so much for the log! 

I know what the issue is now and hopefully will have a chance to fix that this weekend.

**Comment by BiOh424rD** [comment]
Succession.log from IPSW download to kernel panic here:
https://1drv.ms/u/s!Aot6ho0srLCcgeRnuSWP8GjhMNwuZw

> Thanks so much for the log!
> 
> I know what the issue is now and hopefully will have a chance to fix that this weekend.

it is a pleasure, thanks only to you. U are my only chance to restore my iOS 12.2 without blobs.

**Comment by willj2003** [comment]
any update?

**Comment by Samgisaninja** [comment]
I have the issue fixed, but I can't really push an update. I received several (unconfirmed) reports of bootlooping, and until I can figure out why, I cannot push updates or allow the version that potentially caused those bootloops to be used. Hence why 1.4 is disabled at the moment.

**Comment by willj2003** [comment]
Do you just need someone to take one for the team and test it?

**Comment by Samgisaninja** [comment]
No, but I think I've found and fixed the bootloop issue. 

If you'd like to help out, can you please try Succession 1.4.1-b4, available on my test repo, https://samgisaninja.github.io/test/

**Comment by BiOh424rD** [comment]
> No, but I think I've found and fixed the bootloop issue.
> 
> If you'd like to help out, can you please try Succession 1.4.1-b4, available on my test repo, https://samgisaninja.github.io/test/

Not works.
https://1drv.ms/u/s!Aot6ho0srLCcgeRoSAvQxHOCDPVEOA
Soon i’ll Try with the b3 of Unc0ver.

**Comment by Samgisaninja** [comment]
> Not works.

uh, based on that log, it did work

**Comment by BiOh424rD** [comment]
> > Not works.
> 
> uh, based on that log, it did work

I’ve just tried with b3 of unc0ver. But the same, at rebuilding usr /share/locale (with b1) and usr/share/misc (with b3) the app freezes; but after my manual restart the phone seems fully restored but without initial setup. (My backup is on iCloud)

**Comment by Samgisaninja** [comment]
hmm, ok, I have an idea of what's happening, I might need to call `SBDataReset` before restoring xpcproxy and hope that succession doesn't get terminated before that's done. or maybe just completely ignore xpcproxy.

I'll have to do some experimentation with that.

either way, it doesn't crash when attaching any more, so I'm closing this issue.
