### ISSUE TITLE
Crash on ios8.4. Is there a problem with the compiled configuration?

### ISSUE THREAD

**Issue by q741451** [Samgisaninja/SuccessionRestore#68]
download from cydia.saurik.com in cydia
version: 1.4
device: ipod touch 6
system: ios 8.4

Crash immediately after the app opens.
The icon of the app is not displayed properly. so, is there a problem with the compiled configuration for ios8.x?

**Comment by Samgisaninja** [comment]
can you please run `ls -la /Applications/SuccessionRestore.app`

**Comment by q741451** [comment]
> can you please run `ls -la /Applications/SuccessionRestore.app`


iPod-touch:~ root# ls -la /Applications/SuccessionRestore.app
total 2576
drwxr-xr-x  3 root wheel    1020 Oct  4 02:52 ./
drwxrwxr-x 77 root admin    2618 Oct  4 02:52 ../
-rw-r--r--  1 root wheel       0 Sep 30 03:02 .ldid.SuccessionHelper
-rw-r--r--  1 root wheel    1975 Sep 30 03:02 AppIcon20x20\@2x.png
-rw-r--r--  1 root wheel    1975 Sep 30 03:02 AppIcon20x20\@2x~ipad.png
-rw-r--r--  1 root wheel    3016 Sep 30 03:02 AppIcon20x20\@3x.png
-rw-r--r--  1 root wheel     868 Sep 30 03:02 AppIcon20x20~ipad.png
-rw-r--r--  1 root wheel    1369 Sep 30 03:02 AppIcon29x29.png
-rw-r--r--  1 root wheel    3010 Sep 30 03:02 AppIcon29x29\@2x.png
-rw-r--r--  1 root wheel    3010 Sep 30 03:02 AppIcon29x29\@2x~ipad.png
-rw-r--r--  1 root wheel    4789 Sep 30 03:02 AppIcon29x29\@3x.png
-rw-r--r--  1 root wheel    1369 Sep 30 03:02 AppIcon29x29~ipad.png
-rw-r--r--  1 root wheel    4325 Sep 30 03:02 AppIcon40x40\@2x.png
-rw-r--r--  1 root wheel    4325 Sep 30 03:02 AppIcon40x40\@2x~ipad.png
-rw-r--r--  1 root wheel    7773 Sep 30 03:02 AppIcon40x40\@3x.png
-rw-r--r--  1 root wheel    1975 Sep 30 03:02 AppIcon40x40~ipad.png
-rw-r--r--  1 root wheel    7773 Sep 30 03:02 AppIcon60x60\@2x.png
-rw-r--r--  1 root wheel   15656 Sep 30 03:02 AppIcon60x60\@3x.png
-rw-r--r--  1 root wheel   12188 Sep 30 03:02 AppIcon76x76\@2x~ipad.png
-rw-r--r--  1 root wheel    4018 Sep 30 03:02 AppIcon76x76~ipad.png
-rw-r--r--  1 root wheel   13902 Sep 30 03:02 AppIcon83.5x83.5\@2x~ipad.png
-rw-r--r--  1 root wheel  643816 Sep 30 03:02 Assets.car
drwxr-xr-x  4 root wheel     136 Oct  4 02:52 Base.lproj/
-rw-r--r--  1 root wheel    1949 Sep 30 03:02 Info.plist
-rw-r--r--  1 root wheel    1506 Sep 30 03:02 LICENSE.md
-rw-r--r--  1 root wheel   15022 Sep 30 03:02 LaunchImage-700-568h\@2x.png
-rwxr-xr-x  1 root wheel      80 Sep 30 03:02 SuccessionRestore*
-rwxr-xr-x  1 root wheel 1186624 Sep 30 03:02 SuccessionRestore32*
-rwxr-xr-x  1 root wheel  599264 Sep 30 03:02 SuccessionRestore_*
-rwxr-xr-x  1 root wheel   41104 Sep 30 03:02 hdik*
iPod-touch:~ root#

**Comment by q741451** [comment]
> can you please run `ls -la /Applications/SuccessionRestore.app`

I found IPHONEOS_DEPLOYMENT_TARGET = 11 in file compile64.xcconfig.
But IPHONEOS_DEPLOYMENT_TARGET = 8 in file compile32.xcconfig.
Is it related to this?

**Comment by Samgisaninja** [comment]
Delete SuccessionRestore and rename SuccessionRestore32 to SuccessionRestore

**Comment by q741451** [comment]
> Delete SuccessionRestore and rename SuccessionRestore32 to SuccessionRestore

It works! But it says "... this version is disabled until I can investigate ...". Can I continue to wait, for next version?

Thank you very very much!

**Comment by Samgisaninja** [comment]
I tested succession very thoroughly before release and didn't ever have any issues, but there were two people who posted on reddit with bootloop reports, so I disabled it for now. 

If you want to bypass that warning, you can enable airplane mode, tap "Download a filesystem", then exit airplane mode, then "start download".

**Comment by Samgisaninja** [comment]
If possible, could you please run `uname -r` and `uname -p` in terminal/SSH and send the output?

**Comment by q741451** [comment]
iPod-touch:~ root# uname -r
14.0.0
iPod-touch:~ root# uname -p
arm64
iPod-touch:~ root#

**Comment by q741451** [comment]
`[SUCCESSIONLOG 1.4: 2019-10-04 03:38:32 +0000] Line 27: RestoreViewController has loaded!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 188: prepareAttachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 192: Read fstab! /dev/disk0s1s1 / hfs ro 0 1
/dev/disk0s1s2 /private/var hfs rw 0 2

[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 195: Identified filesystem type as HFS! hfs
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 03:38:33 +0000] Line 223: hdik output is: 
......
`
succession.log  above

**Comment by q741451** [comment]
`[SUCCESSIONLOG 1.4: 2019-10-04 04:07:39 +0000] Line 27: RestoreViewController has loaded!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 188: prepareAttachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 192: Read fstab! /dev/disk0s1s1 / hfs ro 0 1
/dev/disk0s1s2 /private/var hfs rw,nosuid,nodev 0 2

[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 195: Identified filesystem type as HFS! hfs
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 210: attachRestoreDisk called!
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 218: Using hdik for attach
[SUCCESSIONLOG 1.4: 2019-10-04 04:07:40 +0000] Line 223: hdik output is: 
....
`
It behaves the same on my iPod touch 5 ios 9.3.5. Is there a problem with some of my operations?

**Comment by Samgisaninja** [comment]
That would be a problem with one of *my* operations lmao. 

What's happening is you're having #48. In 1.4, I tried to fix that by saying "well, if hdik doesn't return any output or can't be read, then [just try it again](https://github.com/Samgisaninja/SuccessionRestore/blob/6e6d153b62c660af45f2bc41eec1c8237a138bc3/SuccessionRestore/RestoreViewController.m#L250)"

That might've been a bad strategy.

**Comment by Samgisaninja** [comment]
That mistake is what's causing #67

**Comment by q741451** [comment]
> That would be a problem with one of _my_ operations lmao.
> 
> What's happening is you're having #48. In 1.4, I tried to fix that by saying "well, if hdik doesn't return any output or can't be read, then [just try it again](https://github.com/Samgisaninja/SuccessionRestore/blob/6e6d153b62c660af45f2bc41eec1c8237a138bc3/SuccessionRestore/RestoreViewController.m#L250)"
> 
> That might've been a bad strategy.

/Applications/SuccessionRestore.app/hdik seems arm64? So it can not work on ipod touch5?

[iPod Touch 5 32bit]
iPod-touch# /Applications/SuccessionRestore.app/hdik
-sh: /Applications/SuccessionRestore.app/hdik: Bad CPU type in executable

[iPod Touch 6 64bit]
iPod-touch# /Applications/SuccessionRestore.app/hdik /private/var/mobile/Media/Succession/rfs.dmg
hdik: attach failed: error 0xe00002c2 = -536870206

**Comment by Samgisaninja** [comment]
This was fixed in succession 1.4.2
