### ISSUE TITLE
Erase all content and settings programatically

### ISSUE THREAD

**Issue by ErikHumphrey** [Samgisaninja/SuccessionRestore#7]
Close this ticket when you figure out how it works; I'm curious too

**Comment by Samgisaninja** [comment]
This is all I've gotten so far: [this dylib](https://nofile.io/f/vYxk2xwMphr/bsr_reset_tweak.dylib) from [BetterSemiRestore](https://web.archive.org/web/20151210053709/http://bettersemirestore.com:80/)

I asked @jk9357- if he had the source to this, he replied he probably did, but hasn't ever sent it

**Comment by Samgisaninja** [comment]
This was added in d0de2d3 and 9041511
