### ISSUE TITLE
Bug with version 1.4.1 

### ISSUE THREAD

**Issue by jonayh** [Samgisaninja/SuccessionRestore#70]
I am unable to restore my xs that’s on 12.4. When I run succession it goes through the steps fine but when it reboots (after rebuilding icons) it’s doesn’t wipe my phone. It does do something as when I go to uncover again it reinstalls everything even tho it’s still present in the devices files.

**Comment by Anthonywillsilv** [comment]
I also have the same issue as above. The only difference is mines on the Xs Max!

**Comment by Samgisaninja** [comment]
Fixed in Succession 1.4.2
