### ISSUE TITLE
1.4.2 Crash on mounting... please wait 

### ISSUE THREAD

**Issue by jonayh** [Samgisaninja/SuccessionRestore#71]
Tried succession 1.4.2 multiple times and it crashes every time on mounting please wait 
Xs 12.4

**Comment by Anthonywillsilv** [comment]
Same on my Xs max

**Comment by Samgisaninja** [comment]
can y'all please run the following as root in terminal and send the output:

`/Applications/SuccessionRestore.app/hdik /var/mobile/Media/Succession/rfs.dmg`

**Comment by Anthonywillsilv** [comment]
hdik: couldn't construct backing store identifier       

I believe I did it right

**Comment by Samgisaninja** [comment]
yeah thanks, that's what I was afraid of

**Comment by jonayh** [comment]
I get permission denied

**Comment by jonayh** [comment]
/rfs.dmg                                           
/dev/disk4              GUID_partition_scheme      
                                                   
/dev/disk4s1            C12A7328-F81F-11D2-BA4B-00A0C93                                                
/dev/disk4s2            7C3457EF-0000-11AA-AA11-0030654                                                
/dev/disk4s2s1          41504653-0000-11AA-AA11-0030654

**Comment by jonayh** [comment]
hdik: no image specified                           
Usage:  hdik [options] <image>                     
        hdik -e <device>                           
        hdik -help                                 
        options:                                   
            -nomount                               
            -drivekey <key>=<value>                
            -encryption <encryption-key+hmacsha1-key>

**Comment by Samgisaninja** [comment]
I think this might be fixed (at least for @jonayh, I have no idea about @Anthonywillsilv but you can try it too) in 3f900f0ab65b7bfb15f16e6e6d994967b4b271fd. 

If y'all would like to try it, please add https://samgisaninja.github.io/test to your sources and update succession.

**Comment by Anthonywillsilv** [comment]
As soon as I get home I’ll try it!

**Comment by Blackeg880** [comment]
The app keep crashing on mounting 
How i can fix 
Iphone xr ios 12.4

**Comment by Anthonywillsilv** [comment]
Ok. I tried restoring. Everything looked ok. Then when it got to the end it said restore completed please wait. So I waited and it just shut my phone off and took my back to my home screen after it restarted. And it deleted my tweaks. That’s all it did. I didn’t get no set up screen

**Comment by Blackeg880** [comment]
Version 1.4.3.b1 fix the crash issu

**Comment by jonayh** [comment]
@Samgisaninja crash issue is fixed but not it’s just hangs on mounting please wait

**Comment by Samgisaninja** [comment]
> So I waited and it just shut my phone off and took my back to my home screen after it restarted. And it deleted my tweaks. That’s all it did. I didn’t get no set up screen

Yeah that's an issue specific to succession when running A12 unc0ver that I'm working with pwn to fix. 


> crash issue is fixed but not it’s just hangs on mounting please wait

@jonayh can you get a log of that happening please?
