### ISSUE TITLE
mobile_obliteration call ignored on u0 substitute

### ISSUE THREAD

**Issue by jonayh** [Samgisaninja/SuccessionRestore#72]
Full restore Option doesn’t work it only does something similar to restore fs

**Comment by Samgisaninja** [comment]
I am aware of it, but somehow there wasn't an issue created on this tracker, so I'll leave this open

**Comment by eaglewolftrades** [comment]
Same. Stuck at “Restore Success! Rebuilding icon cache” prompt. Then reboots without full erase. iPhone XS Max 12.4 Unc0ver

**Comment by bader78** [comment]
any news?

**Comment by Samgisaninja** [comment]
I've been unable to make any progress because cydia impactor broke

**Comment by eaglewolftrades** [comment]
Thank you for the updates

**Comment by jonayh** [comment]
@Samgisaninja was this issue fixed? Or Cydia impactor still not working? I can test your beta apps through appdb or you can yourself

**Comment by Samgisaninja** [comment]
It's fixed, I got off my lazy butt and self-signed. Planning on submitting later tonight.

**Comment by chaqti** [comment]
> It's fixed, I got off my lazy butt and self-signed. Planning on submitting later tonight.

Hasnt fixed for me still reboots are sitting on ui cache then is still on 13.3
