### ISSUE TITLE
Phone reboots after sitting on rebuilding uicache popup for ~2 minutes

### ISSUE THREAD

**Issue by charagarlnad** [Samgisaninja/SuccessionRestore#75]
iPhone XS Max on 12.1.2, after the reboot phone boots back up and is not restored. Generates around 88mb of logs, so I had to trim the repeated lines. 
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/3908646/succession.log)

**Comment by Samgisaninja** [comment]
Duplicate of #72, which was fixed by f73cefc. Release eta son(tm)
