### ISSUE TITLE
Stuck on mounting please wait..

### ISSUE THREAD

**Issue by Silent14725** [Samgisaninja/SuccessionRestore#77]
Hi,

I’m stuck on mounting, please wait tried for many times left my iPhone for an hour on mounting but still no success 

iPhone Xs Max 12.4

**Comment by Silent14725** [comment]
![0BC3AC11-3E93-44B3-8401-01F878732B87](https://user-images.githubusercontent.com/59081558/71239173-ee26e300-2316-11ea-9653-b5d7eee2c0e1.jpeg)

Succession log

**Comment by Samgisaninja** [comment]
Duplicate of #74
