### ISSUE TITLE
“Prepare for Restore Crash”

### ISSUE THREAD

**Issue by syafiqshaary** [Samgisaninja/SuccessionRestore#82]
When all downloding done “prepare for restore” something like create mount point suddenly crashing on iPhone X iOS 13.2.3, Sucession Latest v1.4.5

**Comment by Samgisaninja** [comment]
Can you provide a crash log

**Comment by syafiqshaary** [comment]
https://controlc.com/6c08db5a
This is crash log if you already fix. Sorry im late

**Comment by Samgisaninja** [comment]
As the log states, the crash was caused by bioprotect. I can't fix bioprotect, I can only fix succession.

**Comment by syafiqshaary** [comment]
Thanks :)
