### ISSUE TITLE
No wifi after restore

### ISSUE THREAD

**Issue by markkey014** [Samgisaninja/SuccessionRestore#90]
I’m using an iPhone 7 Plus, but whenever I’m trying to downgrade from iOs 13.3 to 13.2.3, after successfully booting, wifi option is greyed out and not possible to turn on. Tried many times with different version of Succession (1.4.11 etc) and old/newly downloaded ipsw.

**Comment by IMS212** [comment]
Downgrades are unsupported, the most help you’ll get is advice on discord.

**Comment by markkey014** [comment]
I've read on r/ that excluding /usr/share/firmware fix this issue for them, however, I don't have any idea how I can exclude this on restore. Moving on, can you link the discord link?

**Comment by IMS212** [comment]
discord.gg/jb

**Comment by Samgisaninja** [comment]
My stance on downgrading with succession: https://twitter.com/samg_is_a_ninja/status/1221160205142106118?s=21

How to actually fix your issue: https://twitter.com/samg_is_a_ninja/status/1217990624898621446?s=21

**STOP USING OLD VERSIONS**
