### ISSUE TITLE
Attaching Image failed because hdik returned no output. Please reboot and try again

### ISSUE THREAD

**Issue by AhseesMalik** [Samgisaninja/SuccessionRestore#91]
HI sir,
I hope you are fine.
Can you please tell me how can i solve this problem

**Comment by Samgisaninja** [comment]
This was fixed in succession 1.4. 

**STOP USING OLD VERSIONS**

**Comment by AhseesMalik** [comment]
when i used the latest version then it stuck in wait for 10 second

**Comment by Prataps6600** [comment]
Same issue with me with lates succession.,..
