### ISSUE TITLE
Support SE

### ISSUE THREAD

**Issue by gert60** [Samgisaninja/SuccessionRestore#97]
Ate you going to support SE?

**Comment by Samgisaninja** [comment]
the iPhone se is already supported. You may need to provide your own IPSW if apple pulled it. there is nothing I can do about that.

**Comment by gert60** [comment]
Sorry asked because readme said SE not supported.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Sam Gardner <notifications@github.com>
Verzonden: Tuesday, February 4, 2020 12:29:56 AM
Aan: Samgisaninja/SuccessionRestore <SuccessionRestore@noreply.github.com>
CC: gert60 <gharmsen@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Samgisaninja/SuccessionRestore] Support SE (#97)


the iPhone se is already supported. You may need to provide your own IPSW if apple pulled it. there is nothing I can do about that.

**Comment by Samgisaninja** [comment]
yeah it's supported on iOS 10.0 and newer (and might be on all versions by now, that support is controlled by the people at theiphonewiki, as soon as they update their page, Succession 1.4 and newer will gain support without needing a new update to be released)

**Comment by gert60** [comment]
👍🏼 thank you very much

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Sam Gardner <notifications@github.com>
Verzonden: Tuesday, February 4, 2020 12:34:16 AM
Aan: Samgisaninja/SuccessionRestore <SuccessionRestore@noreply.github.com>
CC: gert60 <gharmsen@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Samgisaninja/SuccessionRestore] Support SE (#97)


yeah it's supported on iOS 10.0 and newer (and might be on all versions by now, that support is controlled by the people at theiphonewiki, as soon as they update their page, Succession 1.4 and newer will gain support without needing a new update to be released)
